name: Deploy Terraform

on:
  push
permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          echo "Fetching OIDC Token"
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq


      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::783764585732:role/connectionwithgithubforpipeline
          role-session-name: "samplerolesession"
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Test
          echo "everything fine"

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

# name: AWS OIDC Connect Demo GA
# on:
#   push
# env:
#   AWS_REGION : "eu-west-2"   
# permissions:
#       id-token: write
#       contents: read
# jobs:
#   DemoOIDC:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Git clone the repository
#         uses: actions/checkout@v3

#       - name: configure aws credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: "arn:aws:iam::609009160573:role/GithubopenIDC"
          
#           aws-region: "us-east-1"

#       - name: Print AWS SSM Parameter
#         run: aws ssm get-parameter --name=hello_aws-gh-oidc --query Parameter.Value

#       - name: Print assumed role
#         run: aws sts get-caller-identity
