name: Deploy to EC2 with Approval

on:
  push:
    branches:
      - main   # or your deployment branch

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          echo "Fetching OIDC Token"
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::783764585732:role/connectionwithgithubforpipeline
          role-session-name: "samplerolesession"
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Run tests
        run: echo "Everything fine"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://52.66.241.131  # optional, your EC2 URL

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 52.66.241.131
          username: ec2-user
          key: ${{ secrets.NODEPROJECT }}
          port: 22
          script: |
            if [ -d "/home/ec2-user/Frontend_React_login_signup/.git" ]; then
              echo "Repo exists, pulling latest changes..."
              cd /home/ec2-user/Frontend_React_login_signup
              git pull origin main
            else
              echo "Repo not found, cloning..."
              git clone https://github.com/paras-31/Frontend_React_login_signup.git /home/ec2-user/Frontend_React_login_signup
              cd /home/ec2-user/Frontend_React_login_signup
            fi
            npm install
            npm run build
            pm2 restart all


